### ISSUE TITLE
Segmentation fault when inferencing large size image

### ISSUE THREAD

**Issue by Athenanna** [clovaai/cutblur#4]
thanks for your great work.
And there is the problem **(↓)** when the input image size is [2000,3000,3] (size[<1800, <1800,3] is OK)， if the size of input images is limited? 
`Segmentation fault (core dumped)`
more infoi:
```
torch            1.5.0              
torchfile        0.1.0              
torchvision      0.6.0 

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

GeForce RTX 2080Ti
```

**Comment by nmhkahn** [comment]
Hi @Athenanna 

Perhaps the segmentation fault arises due to the OOM error.
On TITAN X (12GB VRAM), I observed the OOM error when I provide [2000, 3000, 3] HR image (which is [500, 750, 3] LR image).
In this case, I suggest to 1) split LR image into small patches (4 patches normally) 2) sequentially perform SR 3) merge SR patches as in [EDSR-pytorch](https://github.com/thstkdgus35/EDSR-PyTorch/blob/master/src/model/__init__.py#L105)
