### ISSUE TITLE
why crop during evaluation?

### ISSUE THREAD

**Issue by menjarleev** [clovaai/cutblur#7]
Hi I am currently doing some research on data augmentation & SISR. I find that you crop a small margin of HR, SR image during evaluation. Is it because there might be some artifact of produced super-resoluted image that would impact the PSNR result? 

Kind Regards,

**Comment by nmhkahn** [comment]
Hi. @menjarleev 
Cropping the border pixels is conventionally used when evaluating the SR result ([EDSR](https://github.com/thstkdgus35/EDSR-PyTorch/blob/master/src/utility.py#L178), [NTIRE challenge](https://competitions.codalab.org/competitions/18015#learn_the_details-evaluation)).
Not sure why exactly, but I understand that some non-deep SR methods cannot recover the boundaries so that we just cropped it for fair comparison though we can handle.
